modLoader = "javafml"
loaderVersion = "${mod_neo_loader_range}"
issueTrackerURL = "${mod_sources}"
license = "LGPLv3"
logoFile = "${logo_file}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
displayURL="${mod_website}"

[[dependencies.horizontal_glass_panes]]
modId = "neoforge"
type = "required"
versionRange = "${mod_neo_loader_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.horizontal_glass_panes]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.horizontal_glass_panes]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"