# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'gradle'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Copy together artifacts
        shell: bash
        run: |
          mkdir dist
          cp fabric/build/libs/*.jar dist
          cp neoforge/build/libs/*.jar dist
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: dist/*
          
